### ISSUE TITLE
Option to remove non-canonical chromosomes?

### ISSUE THREAD

**Issue by endrebak** [simonvh/genomepy#11]
Some fastas have names like `chr9_UnGL189` etc. that are unwanted in most cases and might cause problems downstream in the pipeline. Would be nice if you had an option that removed these.

It is trivial with pyfaidx: just read the fasta and remove all keys with "_" in them.

**Comment by simonvh** [comment]
However, for some genomes these are the sequences you do want (scaffold_xxx). Might be not that consistent. Have to think on this.

**Comment by endrebak** [comment]
For pro users: be able to give a regex on the cl for which sequences should be removed?

**Comment by simonvh** [comment]
Yes, that could work. Either a negative or positive filter based on a regex.

**Comment by endrebak** [comment]
--match or --not-match. Writing negative regexes can be hard :)

Yes, please think, measure ten times, cut once.
