### ISSUE TITLE
genome_dir argument does not change download folder

### ISSUE THREAD

**Issue by jma1991** [simonvh/genomepy#25]
I want to download a genome to a specific folder, however the genome_dir argument
 does not actually change the download folder:

```
$ genomepy install sacCer3 UCSC -g /home/s1437643/genomes
downloading from http://hgdownload.soe.ucsc.edu/goldenPath/sacCer3/bigZips/chromFa.tar.gz...
done...
name: sacCer3
local name: sacCer3
fasta: /home/s1437643/.local/share/genomes/sacCer3/sacCer3.fa
```

I am using version 0.5.1 from bioconda

**Comment by simonvh** [comment]
Ouch, that is inconvenient, thanks for reporting. I have fixed it and made a new release. It will take some time before I have the release on bioconda.

**Comment by simonvh** [comment]
Release is done, might take a little while before it shows up in bioconda. Feel free to re-open or post another issue if there are still problems.
