### ISSUE TITLE
README on pypi corrupted

### ISSUE THREAD

**Issue by hsiaoyi0504** [simonvh/genomepy#27]
Check this link on pypi https://pypi.org/project/genomepy/0.5.2/.
To solve this issue, check this document on PyPA: https://packaging.python.org/guides/making-a-pypi-friendly-readme/.

**Comment by simonvh** [comment]
Thanks for reporting this. I've been struggling with pypi on and off now, without consistent success. I will try again for the next release :)

**Comment by simonvh** [comment]
Fixed with 0.5.4
