### ISSUE TITLE
Cannot fetch annotations when local name is given.

### ISSUE THREAD

**Issue by dohlee** [simonvh/genomepy#34]
I should thank you first for implementing such a nice and reproducible way to manage the reference genomes!

Unfortunately, I'm now struggling with the error when I tried to attach my own `localname` for the genome. Specifically, when I tried to do

```
genomepy install GRCh38.p12 Ensembl -r '[0-9XY]+$' --annotation -l GRCh38
```
, I get the following error:
```

downloading from https://ftp.ensembl.org//pub/release-95/fasta/homo_sapiens/dna//Homo_sapiens.GRCh38.dna_sm.toplevel.fa.gz...
done...
name: GRCh38.p12
local name: GRCh38
fasta: .../GRCh38/GRCh38.fa
Traceback (most recent call last):
  ...
  (Omitted)
  ...
  File ".../genomepy/functions.py", line 201, in install_genome
    p.download_annotation(name, genome_dir, version=version)
  File ".../genomepy/provider.py", line 389, in download_annotation
    genome_info = self._get_genome_info(name)
  File .../genomepy/provider.py", line 313, in _get_genome_info
    "Could not download genome {} from Ensembl".format(name))
genomepy.exceptions.GenomeDownloadError: Could not download genome GRCh38 from Ensembl
```

Based on the error message, I could deduce that [these code lines](https://github.com/simonvh/genomepy/blob/fbdd7d50dc16e92cc87a04dd5c51991c983034c5/genomepy/functions.py#L190-L197) caused the error. When `localname` is provided, `name` is overridden with `myname` returned from `p.download_genome` method, because `localname` is assigned for `myname` because of [this](https://github.com/simonvh/genomepy/blob/fbdd7d50dc16e92cc87a04dd5c51991c983034c5/genomepy/provider.py#L133-L134). 

I think could immediately fix it, but before that, one thing should be clarified. If `localname` is given, I expect the directory structure and file name will be something like `genome_dir / localname / localname.fa`, and the same rule stands for the annotations like `genome_dir / localname / localname.annotation.gtf.gz`... Is that right? 

If the above becomes clear, I'd file a PR as soon as possible. Thank you!

**Comment by simonvh** [comment]
Thanks for such a clear bug report. Yes, you're right, that is indeed the expected directory and filename structure.
