### ISSUE TITLE
No blacklist found for hg19

### ISSUE THREAD

**Issue by preethiperi** [simonvh/genomepy#43]
Running python 3.6.5 on a pip virtual environment in MacOS Mojave.

Tried to run: genomepy install hg19 UCSC --annotation

Output: 
downloading from http://hgdownload.soe.ucsc.edu/goldenPath/hg19/bigZips/chromFa.tar.gz...
done...
name: hg19
local name: hg19
fasta: /Users/preethiperiyakoil/.local/share/genomes/hg19/hg19.fa
Retrieving gene annotation for hg19
Using http://hgdownload.cse.ucsc.edu/goldenPath/hg19/database/knownGene.txt.gz
zcat: can't stat: /var/folders/v1/r7xw_8yn4v1dbc7y2s5rrjv40000gn/T/tmpsdg3svjr.gz (/var/folders/v1/r7xw_8yn4v1dbc7y2s5rrjv40000gn/T/tmpsdg3svjr.gz.Z): No such file or directory
/Users/preethiperiyakoil/.local/share/genomes/hg19/hg19.annotation.bed.gz already exists -- do you wish to overwrite (y or n)? n
	not overwriting
/Users/preethiperiyakoil/.local/share/genomes/hg19/hg19.annotation.gtf.gz already exists -- do you wish to overwrite (y or n)? n
	not overwriting
No blacklist found for hg19
Downloading blacklist None
'NoneType' object has no attribute 'timeout'
Could not download blacklist file from None

Not sure what this means. I had already run "genomepy plugin enable blacklist". Any suggestions?

**Comment by simonvh** [comment]
Good call, it turns out the hg19 blacklist is missing from the list. I will add that for the next release. (The error message when a blacklist is not found will also be more simple, instead of all these messages).

**Comment by preethiperi** [comment]
Thank you, that would be great!

**Comment by simonvh** [comment]
Fixed in 0.6.0
