### ISSUE TITLE
Download primary assembly by default (if it exists)

### ISSUE THREAD

**Issue by siebrenf** [simonvh/genomepy#45]
GRCh38.p12 (the latest version of the human genome on Ensembl) contains both a Primary Assembly, and a Top-level assembly. The toplevel assembly is downloaded by default, but is 57.9 GB in size. Meanwhile, the primary assembly is 3.2 GB in size. 

It would be preferable to download the primary assembly by default. That said, most organisms (at least on Ensembl) do not have a primary assembly, thus a check would have to be made first.

When both primary and top level assemblies are available, the internet agrees that the primary assembly is sufficient:
- https://bioinformatics.stackexchange.com/questions/540/what-ensembl-genome-version-should-i-use-for-alignments-e-g-toplevel-fa-vs-p 
- http://genomespot.blogspot.com/2015/06/mapping-ngs-data-which-genome-version.html

**Comment by simonvh** [comment]
Fixed in 0.7.0.
