### ISSUE TITLE
Could not download genome Spur_4.2 

### ISSUE THREAD

**Issue by Maarten-vd-Sande** [simonvh/genomepy#51]
$ genomepy search purpuratus
    Ensembl		Spur_3.1	strongylocentrotus_purpuratus
    UCSC		strPur2		S. purpuratus Sep. 2006 (Baylor 2.1/strPur2) Genome at UCSC
    UCSC		strPur1		S. purpuratus Apr. 2005 (Baylor 1.1/strPur1) Genome at UCSC
    NCBI		Spur_5.0	Strongylocentrotus purpuratus; Baylor College of Medicine

Assembly `Spur_4.2` is not in there, however the assembly is still hosted by NCBI: https://www.ncbi.nlm.nih.gov/assembly/GCF_000002235.4/

**Comment by simonvh** [comment]
And it's also still present in `https://ftp.ncbi.nlm.nih.gov/genomes/ASSEMBLY_REPORTS/assembly_summary_refseq_historical.txt`. @siebrenf can you take a look?
